CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'club') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);